[tool.poetry]
name = "forecasting"
version = "0.0.1"
description = ""
authors = ["Amine Laghaout"]
readme = "README.md"
packages = [{include = "forecasting"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
